Update docker-compose.yml

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -1,33 +1,169 @@
+cat > docker-compose.yml << 'EOF'
 services:
-  airflow:
-    image: apache/airflow:2.7.1
+  postgres:
+    image: postgres:13
     environment:
-      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
-      - AIRFLOW__CORE__LOAD_EXAMPLES=True
-      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
-      - AIRFLOW__CORE__BASE_LOG_FOLDER=/opt/airflow/logs
-      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/db/airflow.db
-    command: webserver
-    ports:
-      - 8080:8080
+      POSTGRES_USER: airflow
+      POSTGRES_PASSWORD: airflow
+      POSTGRES_DB: airflow
     volumes:
-      - ./dags:/opt/airflow/dags
-      - ./logs:/opt/airflow/logs
-      - ./db:/opt/airflow/db
-    working_dir: /opt/airflow
+      - postgres_db_volume:/var/lib/postgresql/data
+    healthcheck:
+      test: ["CMD", "pg_isready", "-U", "airflow"]
+      interval: 5s
+      retries: 5
+    restart: always
 
-  scheduler:
+  airflow-webserver:
     image: apache/airflow:2.7.1
     depends_on:
-      - airflow
+      postgres:
+        condition: service_healthy
+      airflow-init:
+        condition: service_completed_successfully
     environment:
-      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
-      - AIRFLOW__CORE__DAGS_FOLDER=/opt/airflow/dags
-      - AIRFLOW__CORE__BASE_LOG_FOLDER=/opt/airflow/logs
-      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=sqlite:////opt/airflow/db/airflow.db
-    command: scheduler
+      AIRFLOW__CORE__EXECUTOR: LocalExecutor
+      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
+      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
+      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
+      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
     volumes:
       - ./dags:/opt/airflow/dags
       - ./logs:/opt/airflow/logs
-      - ./db:/opt/airflow/db
-    working_dir: /opt/airflow
+      - ./config:/opt/airflow/config
+      - ./plugins:/opt/airflow/plugins
+    user: "${AIRFLOW_UID:-50000}:0"
+    command: webserver
+    ports:
+      - "8080:8080"
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
+      interval: 30s
+      timeout: 10s
+      retries: 5
+    restart: always
+
+  airflow-scheduler:
+    image: apache/airflow:2.7.1
+    depends_on:
+      postgres:
+        condition: service_healthy
+      airflow-init:
+        condition: service_completed_successfully
+    environment:
+      AIRFLOW__CORE__EXECUTOR: LocalExecutor
+      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
+      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
+      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
+      AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: 'true'
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
+    volumes:
+      - ./dags:/opt/airflow/dags
+      - ./logs:/opt/airflow/logs
+      - ./config:/opt/airflow/config
+      - ./plugins:/opt/airflow/plugins
+    user: "${AIRFLOW_UID:-50000}:0"
+    command: scheduler
+    healthcheck:
+      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
+      interval: 30s
+      timeout: 10s
+      retries: 5
+    restart: always
+
+  airflow-init:
+    image: apache/airflow:2.7.1
+    depends_on:
+      postgres:
+        condition: service_healthy
+    environment:
+      AIRFLOW__CORE__EXECUTOR: LocalExecutor
+      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
+      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: 'true'
+      AIRFLOW__CORE__LOAD_EXAMPLES: 'true'
+      AIRFLOW__API__AUTH_BACKENDS: 'airflow.api.auth.backend.basic_auth,airflow.api.auth.backend.session'
+      _PIP_ADDITIONAL_REQUIREMENTS: ''
+    volumes:
+      - ./dags:/opt/airflow/dags
+      - ./logs:/opt/airflow/logs
+      - ./config:/opt/airflow/config
+      - ./plugins:/opt/airflow/plugins
+    user: "0:0"
+    command: |
+      bash -c "
+        function ver() {
+          printf \"%04d%04d%04d%04d\" $${1//./ }
+        }
+        airflow_version=$$(AIRFLOW__LOGGING__LOGGING_LEVEL=INFO && airflow version)
+        airflow_version_comparable=$$(ver $${airflow_version})
+        min_airflow_version=2.2.0
+        min_airflow_version_comparable=$$(ver $${min_airflow_version})
+        if (( airflow_version_comparable < min_airflow_version_comparable )); then
+          echo
+          echo -e \"\033[1;31mERROR!!!: Too old Airflow version $${airflow_version}!\e[0m\"
+          echo \"The minimum Airflow version supported: $${min_airflow_version}. Only use this or higher!\"
+          echo
+          exit 1
+        fi
+        if [[ -z \"\$${AIRFLOW_UID}\" ]]; then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: AIRFLOW_UID not set!\e[0m\"
+          echo \"If you are on Linux, you SHOULD follow the instructions below to set \"
+          echo \"AIRFLOW_UID environment variable, otherwise files will be owned by root.\"
+          echo \"For other operating systems you can get rid of the warning with manually created .env file:\"
+          echo \"    See: https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#setting-the-right-airflow-user\"
+          echo
+        fi
+        one_meg=1048576
+        mem_available=$$(($$(getconf _PHYS_PAGES) * $$(getconf PAGE_SIZE) / one_meg))
+        cpus_available=$$(grep -cE 'cpu[0-9]+' /proc/stat)
+        disk_available=$$(df / | tail -1 | awk '{print $$4}')
+        warning_resources=\"false\"
+        if (( mem_available < 4000 )) ; then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: Not enough memory available for Docker.\e[0m\"
+          echo \"At least 4GB of memory required. You have $$(numfmt --to iec $$((mem_available * one_meg)))\"
+          echo
+          warning_resources=\"true\"
+        fi
+        if (( cpus_available < 2 )); then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: Not enough CPUS available for Docker.\e[0m\"
+          echo \"At least 2 CPUs recommended. You have $${cpus_available}\"
+          echo
+          warning_resources=\"true\"
+        fi
+        if (( disk_available < one_meg )); then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: Not enough Disk space available for Docker.\e[0m\"
+          echo \"At least 1 GiB recommended. You have $$(numfmt --to iec $$((disk_available * 1024 )))\"
+          echo
+          warning_resources=\"true\"
+        fi
+        if [[ $${warning_resources} == \"true\" ]]; then
+          echo
+          echo -e \"\033[1;33mWARNING!!!: You have not enough resources to run Airflow (see above)!\e[0m\"
+          echo \"Please follow the instructions to increase amount of resources available:\"
+          echo \"   https://airflow.apache.org/docs/apache-airflow/stable/howto/docker-compose/index.html#before-you-begin\"
+          echo
+        fi
+        mkdir -p /sources/logs /sources/dags /sources/plugins
+        chown -R \"$${AIRFLOW_UID}:0\" /sources/{logs,dags,plugins}
+        exec /entrypoint airflow db init
+        if [ \"$$?\" -eq 0 ]; then
+          airflow users create \\
+            --username admin \\
+            --firstname Peter \\
+            --lastname Parker \\
+            --role Admin \\
+            --email spiderman@superhero.org \\
+            --password admin
+        fi
+      "
+
+volumes:
+  postgres_db_volume:
+EOF
